### PR TITLE
Add wally package

### PR DESCRIPTION
**Pull request by eldonwilliams**
I published this package as eldonwilliams/spr if you want to use it right now, but I would like to see this merged to master and published under fraktality/spr.

*When this is merged, README.md will have to have the wally installation instructions tweaked slightly.*

### CODE REVIEW

**Comment by fraktality** [comment]
Thanks for the PR!
This makes unrelated changes to the spr datatypes so I can't accept it as-is.

**Comment by eldonwilliams** [comment]
Sorry about that. I was using it for my own implementation and the changes accidentally carried over. I'll try and fix it once I get home, thanks.

**Comment by Nidoxs** [comment]
I assume this is not already within the Wally index? I don't want to upload a duplicate if you do plan to add this yourself as the official source on Wally. @Fraktality

**Comment by fraktality** [comment]
I have no plans to add spr to Wally.
Feel free to add it as long as you make it clear that it's not endorsed by me.

**Pull request closed without merging**
