### PR TITLE
Add spr.cancelCompleted() function

### PR DESCRIPTION
**Pull request by cagoshian**
This new function cancels all registered callbacks for the given instance. 
I needed this function, to delete a UI element after the animation, but cancel the deletion if a new interaction comes in.
Also, I fixed a small issue in spr.completed's example code.

### CODE REVIEW

**Comment by fraktality** [comment]
I've merged a fix for the readme, thanks.
I think this API should be structed differently; `spr.completed` should return a function that cancels this callback.

**Comment by cagoshian** [comment]
`local callback = spr.completed(workspace.Part, function() workspace.Part:Destroy() end)`
`callback.cancel()`
something like this?

**Comment by fraktality** [comment]
```lua
local cancel = spr.completed(part, function() part:Destroy() end)
cancel()
```

**Comment by cagoshian** [comment]
I think creating a new function would be better for usability between scripts. For example, I create a completed callback on a script, but will handle interactions and cancel callbacks on another script.

But, if you think that returning a function to cancel is a better method, I can publish a new commit for it.

**Comment by fraktality** [comment]
I think returning a callback is strictly more flexible because it allows you to cancel callbacks individually. You can also hook this to maids/destructors directly for fast cleanup: `dtor:add(spr.completed(...))`

**Comment by cagoshian** [comment]
I opened a new pull request, for this method of canceling callback

**Pull request closed without merging**
